var main = function() {
  $('.banner').click(function(){
      $(this).next().slideToggle("fast");
  });
  $('.search input').keyup(function(){
    var $search = $(this).val().toLowerCase();
    console.log("search for: "+$search);
    $('.desc').hide();
    $('.banner .civname').each(function(){
      $(this).parent().show();
      if ($search==='') {
        $(this).parent().show();
      }else if($(this).text().toLowerCase().search($search) >= 0||$(this).next().next().text().toLowerCase().search($search) >= 0) {
      } else {
        $(this).parent().hide();
      }
    });
  });
  $('.random button').click(function(){
    var $numCivs = $('.banner').length;
    var random = Math.floor(Math.random()*($numCivs));
    $('.desc').hide();
    $('.banner').hide();
    console.log(random+": random civ is "+ $('.banner .civname').eq(random).text());
    $('.banner').eq(random).show();
    
  });
};

$(document).ready(main);

var civApp = angular.module("civApp",[]);


civApp.controller('civCtrl', ['$scope', function($scope){
	$scope.civs = [{
		civName:'America',
		civIcon:'america',
		leaderName: 'Washington',
		leaderIcon: 'washington',
		colorlight: '#5570d3',
		colordark: '#10193d',
		fontcolor: '#FFFFFF',
		abilityname: 'Manifest Destiny',
		ability: 'All land military units have +1 sight. 50% discount when purchasing tiles.',
		unique1name: 'B17',
		unique1icon: 'b17.png',
		unique1desc: 'Unique American Bomber.<br />It is more difficult for enemy anti-aircraft and fighters to target and receives a bonus when attacking enemy cities.<br />Cost: 375 <img src="img/civ/production.png"><br />Strength: 70<img src="img/civ/ranged.png"><br />Range: 10<br /> Movement: 2 <img src="img/civ/movement.png">',
		unique2name: 'Minuteman',
		unique2icon: 'minuteman.png',
		unique2desc: 'Unique American Musketman. <br />This Unit may move through rough ground as though it were flat, receives a bonus when fighting in rough terrain, and earns points toward a <img src="img/civ/golden_age.png"> Golden Age when it defeats an enemy.<br />Cost: 150 <img src="img/civ/production.png"> or 300 <img src="img/civ/faith.png"><br />Strength: 24 <img src="img/civ/strength.png"><br />Movement: 2 <img src="img/civ/movement.png">'
	}, {
		civName:'Arabia',
		civIcon:'arabia',
		leaderName: 'Harun al-Rashid',
		leaderIcon: 'harun',
		colorlight: '#51a455',
		colordark: '#1e3e20',
		fontcolor: '#92DD09',
		abilityname: 'Ships of the Desert',
		ability: 'Caravans gain 50% extended range. Your trade routes spread the home city\'s religion twice as effectively. <img src="img/civ/oil.png"> Oil resources are doubled.',
		unique1name: 'Bazaar',
		unique1icon: 'bazaar.png',
		unique1desc: 'Unique Arabian Market.<br />Cost: 100 <img src="img/civ/production.png"> or 500 <img src="img/civ/gold.png"><br />+2 <img src="img/civ/gold.png">Gold<br />+25\% <img src="img/civ/gold.png"> Gold per turn<br />Provides 1 extra copy of each improved luxury resource near this City. Each source of <img src="img/civ/oil.png"> Oil and each Oasis provides +2 <img src="img/civ/gold.png"> Gold.',
		unique2name: 'Camel Archer',
		unique2icon: 'camelarcher.png',
		unique2desc: 'Unique Arabian Knight.<br />Fast Medieval ranged Unit, weak to Pikemen. Only the Arabians may build it. It is a ranged unit, unlike the Knight which it replaces.<br />Cost: 120 <img src="img/civ/production.png"> or 240 <img src="img/civ/faith.png"><br />Strength: 17 <img src="img/civ/strength.png">or 21 <img src="img/civ/ranged.png"><br />Movement: 4 <img src="img/civ/movement.png">'
	}, {
		civName:'Assyria',
		civIcon:'assyria',
		leaderName: 'Ashurbanipal',
		leaderIcon: 'ashurbanipal',
		colorlight: '#fff8d1',
		colordark: '#b89c00',
		fontcolor: '#b37400',
		abilityname: 'Treasures of Nineveh',
		ability: 'When a city is conquered, gain a free Technology already discovered by its owner. Gaining a city through a trade deal does not count, and it can only happen once per enemy city.',
		unique1name: 'Royal Library',
		unique1icon: 'royallibrary.png',
		unique1desc: 'Unique Assyrian Library.<br />Cost: 75 <img src="img/civ/production.png"> or 320 <img src="img/civ/gold.png"><br />Has a slot for a Great Work of Writing which, when filled, gives extra XP to trained Units.',
		unique2name: 'Siege Tower',
		unique2icon: 'siegetower.png',
		unique2desc: 'Unique Assyrian Catapult<br />Cost: 75 <img src="img/civ/production.png"> or 150 <img src="img/civ/faith.png"><br />Strength: 12 <img src="img/civ/strength.png"><br />Movement: 2 <img src="img/civ/movement.png">'
	}, {
		civName:'Austria',
		civIcon:'austria',
		leaderName: 'Maria Theresa',
		leaderIcon: 'maria_theresa',
		colorlight: '#ff3838',
		colordark: '#940000',
		fontcolor: '#FFFFFF',
		abilityname: 'Diplomatic Marriage',
		ability: 'Can spend <img src="img/civ/gold.png"> Gold to annex or puppet a City-State that has been your ally for 5 turns.',
		unique1name: 'Coffee House',
		unique1icon: 'coffeehouse.png',
		unique1desc: 'Unique Austrian Windmill<br />Cost: 250 <img src="img/civ/production.png"> or 1000 <img src="img/civ/gold.png"><br />+2 <img src="img/civ/production.png"> Production<br />+5% <img src="img/civ/production.png"> Production per turn<br />+25% <img src="img/civ/great_people.png"> Great People generation in this City.<br />',
		unique2name: 'Hussar ',
		unique2icon: 'hussar.png',
		unique2desc: 'Unique Austrian Cavalry<br />They are faster than cavalry, and start with Promotions that give them +1 Sight and increases their bonus when making a Flank Attack by 50%.<br />Cost: 255 <img src="img/civ/production.png"><br />Strength: 34 <img src="img/civ/strength.png"><br />Movement: 5 <img src="img/civ/movement.png">'
	}, {
		civName:'The Aztecs',
		civIcon:'aztec',
		leaderName: 'Montezuma',
		leaderIcon: 'montezuma',
		colorlight: '#bd4428',
		colordark: '#7e2d1b',
		fontcolor: '#88EED4',
		abilityname: 'Sacrificial Captives',
		ability: 'Gains <img src="img/civ/culture.png"> Culture for the empire from each enemy unit killed.',
		unique1name: 'Floating Gardens',
		unique1icon: 'floatinggardens.png',
		unique1desc: 'Unique Aztec Water Mill<br />Cost: 75 <img src="img/civ/production.png"> or 400 <img src="img/civ/gold.png"><br />+15% <img src="img/civ/food.png"> Food. <br />Each worked Lake tile provides +2 <img src="img/civ/food.png"> Food.<br />City must be built next to a River or Lake.',
		unique2name: 'Jaguar',
		unique2icon: 'jaguar.png',
		unique2desc: 'Unique Aztec Warrior<br /> This Unit fights more effectively in Jungle and heals damage when it kills an enemy Unit.<br />Cost: 40 <img src="img/civ/production.png"> or 80 <img src="img/civ/faith.png"><br />Strength: 8 <img src="img/civ/strength.png"><br />Movement: 2 <img src="img/civ/movement.png">'
	}, {
		civName:'Babylon',
		civIcon:'babylon',
		leaderName: 'Nebuchadnezzar',
		leaderIcon: 'nebuchadnezzar',
		colorlight: '#5196b3',
		colordark: '#213e4a',
		fontcolor: '#C8F8FF',
		abilityname: 'Ingenuity',
		ability: 'Receive free Great Scientist when you discover Writing. Earn Great Scientists 50% faster.',
		unique1name: 'Walls of Babylon',
		unique1icon: 'walls_of_babylon.png',
		unique1desc: 'Unique Babylonian Wall<br />Cost: 65 <img src="img/civ/production.png"> or 360 <img src="img/civ/gold.png"><br />The Walls of Babylon increase the damage output of all the city\'s ranged attacks and increase the city\'s defense.',
		unique2name: 'Bowman',
		unique2icon: 'bowman.png',
		unique2desc: 'Unique Babylonian Archer<br /> The Bowman can better withstand melee attacks than the standard Archer available to other civs.<br />Cost: 40 <img src="img/civ/production.png"> or 80 <img src="img/civ/faith.png"><br />Strength: 7 <img src="img/civ/strength.png"> or 9 <img src="img/civ/ranged.png"><br />Movement: 2 <img src="img/civ/movement.png">'
	}, {
		civName:'Brazil',
		civIcon:'brazil',
		leaderName: 'Pedro II',
		leaderIcon: 'pedro',
		colorlight: '#d1f980',
		colordark: '#678410',
		fontcolor: '#29532C',
		abilityname: 'Carnival',
		ability: 'Tourism output is +100% during their Golden Ages. Earn Great Artists, Musicians, and Writers 50% faster during their Golden Ages.',
		unique1name: 'Brazilwood Camp',
		unique1icon: 'brazilwood-camp.png',
		unique1desc: 'Unique Brazillian Tile Improvement<br />May only be built on Jungle<br /> +2 <img src="img/civ/gold.png"> Gold<br />+2 <img src="img/civ/culture.png"> Culture  after Acoustics',
		unique2name: 'Pracinha',
		unique2icon: 'pracinha.png',
		unique2desc: 'Unique Brazillian Infantry.<br />Earns points toward a <img src="img/civ/golden_age.png"> Golden Age when it defeats an enemy.<br />Cost: 375 <img src="img/civ/production.png"> or 750 <img src="img/civ/faith.png"><br />Strength:70<img src="img/civ/strength.png"><br />Movement: 2 <img src="img/civ/movement.png">'
	}, {
		civName:'Byzantium',
		civIcon:'byzantium',
		leaderName: 'Theodora',
		leaderIcon: 'theodora',
		colorlight: '#91b6ed',
		colordark: '#3a7cdf',
		fontcolor: '#3C006C',
		abilityname: 'Patriarchate of Constantinople',
		ability: 'Choose one more Belief than normal when you found a Religion.',
		unique1name: 'Dromon',
		unique1icon: 'dromon.png',
		unique1desc: 'Unique Byzantine Trireme<br />Dominant Ancient Era Naval Unit used to own the seas through the Classic Era with its ranged attack.<br />Cost: 56 <img src="img/civ/production.png"><br />Strength: 8 <img src="img/civ/strength.png"> or 10 <img src="img/civ/ranged.png"><br />Movement: 4 <img src="img/civ/movement.png">',
		unique2name: 'Cataphract',
		unique2icon: 'cataphract.png',
		unique2desc: 'Unique Byzantine Horseman<br />This Unit has a higher Strength, defends better, and attacks cities more effectively than the Horseman which it replaces.<br />Cost: 75 <img src="img/civ/production.png"> or 150 <img src="img/civ/faith.png"><br />Strength: 15 <img src="img/civ/strength.png"><br />Movement: 3 <img src="img/civ/movement.png">'
	}, {
		civName:'Carthage',
		civIcon:'carthage',
		leaderName: 'Dido',
		leaderIcon: 'dido',
		colorlight: '#dedede',
		colordark: '#9e9e9e',
		fontcolor: '#500088',
		abilityname: 'Phoenician Heritage',
		ability: 'All coastal Cities get a free Harbor. Units may cross mountains after the first Great General is earned, taking 50 HP damage if they end a turn on a mountain.',
		unique1name: 'Quinquereme',
		unique1icon: 'quinquereme.png',
		unique1desc: 'Unique Carthagian Trireme<br >Strong Ancient Era Naval Unit used to dominate the seas through melee attacks on naval units and cities.<br />Cost: 45 <img src="img/civ/production.png"><br />Strength: 13 <img src="img/civ/strength.png"><br />Movement: 4 <img src="img/civ/movement.png">',
		unique2name: 'African Forest Elephant',
		unique2icon: 'forestelephant.png',
		unique2desc: 'Unique Carthagian Horseman<br >This Unit has a higher <img src="img/civ/strength.png"> Combat Strength than the Horseman which it replaces and strikes fear into nearby enemy units. Helps produce Great Generals more quickly.<br />Cost: 100 <img src="img/civ/production.png"> or 200 <img src="img/civ/faith.png"><br />Strength: 14 <img src="img/civ/strength.png"><br />Movement: 3 <img src="img/civ/movement.png">'
	}, {
		civName:'The Celts',
		civIcon:'celts',
		leaderName: 'Boudicca',
		leaderIcon: 'boudicca',
		colorlight: '#1d8157',
		colordark: '#104730',
		fontcolor: '#93A9FF',
		abilityname: 'Druidic Lore',
		ability: '+1 <img src="img/civ/faith.png"> Faith per city with an adjacent unimproved Forest. Bonus increases to +2 <img src="img/civ/faith.png"> Faith in Cities with 3 or more adjacent unimproved Forest tiles.',
		unique1name: 'Ceilidh Hall',
		unique1icon: 'ceilidhhall.png',
		unique1desc: 'Unique Celtic Opera House<br />Cost: 200 <img src="img/civ/production.png"> or 740 <img src="img/civ/gold.png"><br />+3 <img src="img/civ/happiness.png"> Happiness<br />+1 <img src="img/civ/culture.png"> Culture<br />1 Great Work of Music slot',
		unique2name: 'Pictish Warrior',
		unique2icon: 'pictishwarrior.png',
		unique2desc: 'Unique Celtic Spearman<br />Has a combat bonus outside of friendly territory and can pillage enemy improvements at no additional movement cost. Earns 50% of opponents\' strength as peace Faith for kills.<br />Cost: 56 <img src="img/civ/production.png"> or 112 <img src="img/civ/faith.png"><br />Strength: 11 <img src="img/civ/strength.png"><br />Movement: 2 <img src="img/civ/movement.png">'
	}, {
		civName:'China',
		civIcon:'china',
		leaderName: 'Wu Zetian',
		leaderIcon: 'wu',
		colorlight: '#00c76d',
		colordark: '#006b3b',
		fontcolor: '#FFFFFF',
		abilityname: 'Art of War',
		ability: 'The Great General combat bonus is increased by 15%, and their spawn rate is increased by 50%.',
		unique1name: 'Paper Maker',
		unique1icon: 'papermaker.png',
		unique1desc: 'Unique Chinese Library<br />Cost: 75 <img src="img/civ/production.png"> or 400 <img src="img/civ/gold.png"><br />In addition to the Science boost of the library, it also provides a boost to the city\'s intake of <img src="img/civ/gold.png"> Gold.<br />+2 <img src="img/civ/gold.png"> Gold<br />+1 <img src="img/civ/science.png"> Science per 2 <img src="img/civ/citizen.png"> Citizens',
		unique2name: 'Chu-Ko-Nu',
		unique2icon: 'chukonu.png',
		unique2desc: 'Unique Chinese Crossbowman<br />This Unit may fire twice in one turn.<br />Cost: 120 <img src="img/civ/production.png"> or 240 <img src="img/civ/faith.png"><br />Strength: 13 <img src="img/civ/strength.png"> or 14 <img src="img/civ/ranged.png"><br />Range: 2<br />Movement: 2 <img src="img/civ/movement.png">'
	}, {
		civName:'Denmark',
		civIcon:'denmark',
		leaderName: 'Harald Bluetooth',
		leaderIcon: 'harald',
		colorlight: '#973a1c',
		colordark: '#41190c',
		fontcolor: '#EFE7B3',
		abilityname: 'Viking Fury',
		ability: 'Embarked units have +1 <img src="img/civ/movement.png"> Movement and pay just 1 movement point to move from sea to land. Melee units pay no movement point cost to pillage.',
		unique1name: 'Berserker',
		unique1icon: 'berserker.png',
		unique1desc: 'Unique Danish Longswordsman<br />Strong, front-line land Unit of the Medieval Era that specializes in attacks from the sea. Replaces the Longswordsman, but is available earlier.<br />Cost: 120 <img src="img/civ/production.png"> or 240 <img src="img/civ/faith.png"><br />Strength: 21 <img src="img/civ/strength.png"><br />Movement: 3 <img src="img/civ/movement.png">',
		unique2name: 'Norwegian Ski Infantry',
		unique2icon: 'skiinfantry.png',
		unique2desc: 'Unique Danish Rifleman<br />Strong, front-line land Unit of the mid-game that specializes in operating in Snow, Tundra and Hills.<br />Cost: 225 <img src="img/civ/production.png"> or 450 <img src="img/civ/faith.png"><br />Strength: 34 <img src="img/civ/strength.png"><br />Movement: 2 <img src="img/civ/movement.png">'
	}, {
		civName:'Egypt',
		civIcon:'egypt',
		leaderName: 'Ramesses II',
		leaderIcon: 'ramesses',
		colorlight: '#fffc2e',
		colordark: '#bdba00',
		fontcolor: '#5200D0',
		abilityname: 'Monument Builders',
		ability: '+20% <img src="img/civ/production.png"> Production towards Wonder construction.',
		unique1name: 'Burial Tomb',
		unique1icon: 'burialtomb.png',
		unique1desc: 'Unique Egyptian Temple<br />Cost: 100 <img src="img/civ/production.png"> or 500 <img src="img/civ/gold.png"><br />+2 <img src="img/civ/happiness.png"> Happiness<br />Requires no gold Gold maintenance.<br />Should this city be captured, the amount of <img src="img/civ/gold.png"> Gold plundered by the enemy is doubled.',
		unique2name: 'War Chariot',
		unique2icon: 'warchariot.png',
		unique2desc: 'Unique Egyptian Chariot Archer<br />Faster than the Chariot Archer and does not require horses Horses to be built.<br />Cost: 56 <img src="img/civ/production.png"> or 112 <img src="img/civ/faith.png"><br />Strength: 6 <img src="img/civ/strength.png"> or 10 <img src="img/civ/ranged.png"><br />Movement: 5 <img src="img/civ/movement.png">'
	}, {
		civName:'England',
		civIcon:'england',
		leaderName: 'Elizabeth',
		leaderIcon: 'elizabeth',
		colorlight: '#a30300',
		colordark: '#570100',
		fontcolor: '#FFFFFF',
		abilityname: 'Sun Never Sets',
		ability: '+2 <img src="img/civ/movement.png"> Movement for all naval units. Receives 1 extra Spy.',
		unique1name: 'Longbowman',
		unique1icon: 'longbowman.png',
		unique1desc: 'Unique English Crossbowman<br />This Unit has 1 additional range compared to the Crossbowman, which it replaces.<br />Cost: 120 <img src="img/civ/production.png"> or 240 <img src="img/civ/faith.png"><br />Strength: 13 <img src="img/civ/strength.png"> or 18 <img src="img/civ/ranged.png"><br />Movement: 2 <img src="img/civ/movement.png">',
		unique2name: 'Ship of the Line',
		unique2icon: 'shipoftheline.png',
		unique2desc: 'Unique English Frigate<br />The Ship of the Line has a slightly higher Ranged Combat strength than the Frigate, and it\'s slightly cheaper to produce. It can see one hex farther than the Frigate, allowing it to spot enemies in a significantly larger section of ocean.<br />Cost: 170 <img src="img/civ/production.png"><br />Strength: 30 <img src="img/civ/strength.png"> or 35 <img src="img/civ/ranged.png"><br />Range: 2<br />Movement: 5 <img src="img/civ/movement.png">'
	}, {
		civName:'Ethiopia',
		civIcon:'ethiopia',
		leaderName: 'Haile Selassie',
		leaderIcon: 'haile',
		colorlight: '#025e23',
		colordark: '#011e0b',
		fontcolor: '#FF2D2D',
		abilityname: 'Spirit of Adwa',
		ability: 'Combat bonus (+20%) when fighting units from a Civilization with more Cities than Ethiopia.',
		unique1name: 'Stele',
		unique1icon: 'stele.png',
		unique1desc: 'Unique Ethiopian Monument<br />Cost: 40 <img src="img/civ/production.png"> or 200 <img src="img/civ/gold.png"><br />+2 <img src="img/civ/culture.png"> Culture<br />+2 <img src="img/civ/faith.png"> Faith',
		unique2name: 'Mehal Sefari',
		unique2icon: 'mehal.png',
		unique2desc: 'Unique Ethiopian Rifleman<br />They start with promotions that give them bonuses fighting in rough terrain and near their capital. They are slightly cheaper to build than the Rifleman that they replace.<br />Cost: 200 <img src="img/civ/production.png"><br />Strength: 34 <img src="img/civ/strength.png"><br />Movement: 2 <img src="img/civ/movement.png">'
	}, {
		civName:'France',
		civIcon:'france',
		leaderName: 'Napoleon',
		leaderIcon: 'napoleon',
		colorlight: '#62a0fd',
		colordark: '#0256d4',
		fontcolor: '#EBEB8A',
		abilityname: 'City of Light',
		ability: 'Museum and World Wonder theming bonuses are doubled in their capital.',
		unique1name: 'Chateau',
		unique1icon: 'chateau.png',
		unique1desc: 'Unique French Tile Improvement<br />May only be built adjacent to a luxury resource, and not adjacent to another Chateau<br />+1 <img src="img/civ/gold.png"> Gold, +3 <img src="img/civ/gold.png"> Gold after Flight<br />+2 <img src="img/civ/culture.png"> Culture, +3 <img src="img/civ/culture.png"> Culture after Flight',
		unique2name: 'Musketeer',
		unique2icon: 'musketeer.png',
		unique2desc: 'Unique French Musketman<br />This Unit has a higher Strength than the Musketman, which it replaces.<br />Cost: 150 <img src="img/civ/production.png"> or 300 <img src="img/civ/faith.png"><br />Strength: 28 <img src="img/civ/strength.png"><br />Movement: 2 <img src="img/civ/movement.png">'
	}, {
		civName:'Germany',
		civIcon:'germany',
		leaderName: 'Bismarck',
		leaderIcon: 'bismarck',
		colorlight: '#c8c7cc',
		colordark: '#8f8c97',
		fontcolor: '#242B20',
		abilityname: 'Furor Teutonicus',
		ability: 'Upon defeating a Barbarian unit inside an encampment, there is a 67% chance you earn 25 <img src="img/civ/gold.png"> Gold and they join your side. Pay 25% less for land unit maintenance.',
		unique1name: 'Hanse',
		unique1icon: 'hanse.png',
		unique1desc: 'Unique German Bank<br />Cost: 200 <img src="img/civ/production.png"> or 740 <img src="img/civ/gold.png"><br />+2 <img src="img/civ/gold.png"> Gold<br />+25% <img src="img/civ/gold.png"> Gold per turn<br />+5% <img src="img/civ/production.png"> Production for each Trade Route your civilization has with a City-State.',
		unique2name: 'Panzer',
		unique2icon: 'panzer.png',
		unique2desc: 'Unique German Tank<br />This Unit is stronger and has 1 additional movement compared to the Tank, which it replaces.<br />Cost: 375 <img src="img/civ/production.png"> or 750 <img src="img/civ/faith.png"><br />Strength: 80 <img src="img/civ/strength.png"><br />Movement: 6 <img src="img/civ/movement.png">'
	}, {
		civName:'Greece',
		civIcon:'greece',
		leaderName: 'Alexander',
		leaderIcon: 'alexander',
		colorlight: '#ffffff',
		colordark: '#b2f4fb',
		fontcolor: '#418DFD',
		abilityname: 'Hellenic League',
		ability: 'City-State <img src="img/civ/influence.png"> Influence degrades at half and recovers at twice the normal rate.',
		unique1name: 'Companion Cavalry',
		unique1icon: 'companioncavalry.png',
		unique1desc: 'Unique Greek Horseman<br />This Unit is faster, has a higher Strength and helps produce Great Generals more quickly than the Horseman which it replaces.<br />Cost: 75 <img src="img/civ/production.png"> or 150 <img src="img/civ/faith.png"><br />Strength: 14 <img src="img/civ/strength.png"><br />Movement: 5 <img src="img/civ/movement.png">',
		unique2name: 'Hoplite',
		unique2icon: 'hoplite.png',
		unique2desc: 'Unique Greek Spearman<br /> This Unit has a higher Strength than the Spearman which it replaces.<br />Cost: 56 <img src="img/civ/production.png"> or 112 <img src="img/civ/faith.png"><br />Strength: 13 <img src="img/civ/strength.png"><br />Movement: 2 <img src="img/civ/movement.png">'
	}, {
		civName:'India',
		civIcon:'india',
		leaderName: 'Gandhi',
		leaderIcon: 'gandhi',
		colorlight: '#18aa08',
		colordark: '#107005',
		fontcolor: '#FF9931',
		abilityname: 'Population Growth',
		ability: '<img src="img/civ/unhappiness.png"> Unhappiness from number of Cities doubled, <img src="img/civ/unhappiness.png"> Unhappiness from number of <img src="img/civ/citizen.png"> Citizens halved.',
		unique1name: 'Mughal Fort',
		unique1icon: 'mughalfort.png',
		unique1desc: 'Unique Indian Castle<br />Cost: 150 <img src="img/civ/production.png"> or 680 <img src="img/civ/gold.png"><br />+2 <img src="img/civ/culture.png"> Culture<br />+2 <img src="img/civ/tourism.png"> Tourism after Flight',
		unique2name: 'War Elephant',
		unique2icon: 'warelephant.png',
		unique2desc: 'Unique Indian Chariot Archer<br />This Unit has a higher Combat and Ranged Strength than the Chariot Archer, which it replaces.<br />Cost: 70 <img src="img/civ/production.png"> or 140 <img src="img/civ/faith.png"><br />Strength: 9 <img src="img/civ/strength.png"> or 11 <img src="img/civ/ranged.png"><br />Range: 2<br />Movement: 3 <img src="img/civ/movement.png">'
	}, {
		civName:'The Huns',
		civIcon:'huns',
		leaderName: 'Attila',
		leaderIcon: 'attila',
		colorlight: '#c3c2b6',
		colordark: '#9f9c89',
		fontcolor: '#450003',
		abilityname: 'Scourge of God',
		ability: 'Raze Cities at double speed. Borrow City names from other in-game Civs. Start with Animal Husbandry technology. +1 <img src="img/civ/production.png"> Production per Pasture.',
		unique1name: 'Battering Ram',
		unique1icon: 'batteringram.png',
		unique1desc: 'Unique Hunnic Spearman Replacement<br />Siege unit deadly at melee attacks versus cities.<br />Cost: 75 <img src="img/civ/production.png"> or 150 <img src="img/civ/faith.png"><br />Strength: 10 <img src="img/civ/strength.png"><br />Movement: 2 <img src="img/civ/movement.png">',
		unique2name: 'Horse Archer',
		unique2icon: 'horsearcher.png',
		unique2desc: 'Unique Hunnic <br /> They are slightly stronger in defense than the Chariot Archer and can move through rough terrain without the Chariot Archer\'s movement penalty. They also start with the Accuracy I promotion. Does not require horses<br />Cost: 56 <img src="img/civ/production.png"> or 112 <img src="img/civ/faith.png"><br />Strength: 7 <img src="img/civ/strength.png"> or 10 <img src="img/civ/ranged.png"> <br />Movement: 2 <img src="img/civ/movement.png">'
	}, {
		civName:'The Inca',
		civIcon:'inca',
		leaderName: 'Pachacuti',
		leaderIcon: 'pachacuti',
		colorlight: '#ffcb5c',
		colordark: '#ffb30f',
		fontcolor: '#069F77',
		abilityname: 'Great Andean Road',
		ability: 'Units ignore terrain costs when moving into any tile with Hills. No maintenance costs for improvements in Hills; half cost elsewhere.',
		unique1name: 'Terrace Farm',
		unique1icon: 'terracefarm.png',
		unique1desc: 'Unique Incan Tile Improvement<br />May only be built on hills<br />+1 <img src="img/civ/food.png"> Food<br />+1 <img src="img/civ/food.png">additional Food for every adjacent mountain tile<br />',
		unique2name: 'Slinger',
		unique2icon: 'slinger.png',
		unique2desc: 'Unique Incan Archer<br />Possesses a promotion that gives it a good chance to withdraw to the rear before an enemy melee attack can occur.<br />Cost: 40 <img src="img/civ/production.png"> or 80 <img src="img/civ/faith.png"><br />Strength: 4 <img src="img/civ/strength.png"> or 7 <img src="img/civ/ranged.png"><br />Range: 2 <br />Movement: 2 <img src="img/civ/movement.png">'
	}, {
		civName:'Indonesia',
		civIcon:'indonesia',
		leaderName: 'Gaja Mada',
		leaderIcon: 'gaja',
		colorlight: '#92dde2',
		colordark: '#36c0c9',
		fontcolor: '#9E2E1C',
		abilityname: 'Spice Islanders',
		ability: 'The first 3 cities founded on continents other than where Indonesia started each provide 2 unique Luxury Resources (and can never be razed).',
		unique1name: 'Candi',
		unique1icon: 'candi.png',
		unique1desc: 'Unique Indonesian Garden<br />Cost: 120 <img src="img/civ/production.png"> or 580 <img src="img/civ/gold.png"><br />Unlike the Garden the Candi does not have to be built next to a River or Lake.<br />+2 <img src="img/civ/faith.png"> Faith for each World Religion that has at least 1 follower in the city<br />+25% <img src="img/civ/great_people.png"> Great People generation in this City',
		unique2name: 'Kris Swordsman',
		unique2icon: 'krisswordsman.png',
		unique2desc: 'Unique Indonesian Swordsman<br />Has a mystical weapon whose abilities will be discovered the first time it is used in combat.<br />Cost: 75 <img src="img/civ/production.png"> or 150 <img src="img/civ/faith.png"><br />Strength: 14 <img src="img/civ/strength.png"><br />Movement: 2 <img src="img/civ/movement.png">'
	}, {
		civName:'The Iroquois',
		civIcon:'iroquois',
		leaderName: 'Hiawatha',
		leaderIcon: 'hiawatha',
		colorlight: '#516c6c',
		colordark: '#394c4c',
		fontcolor: '#FBC981',
		abilityname: 'The Great Warpath',
		ability: 'Units move through Forest and Jungle in friendly territory as if they were Roads. These tiles can be used to establish <img src="img/civ/connected.png"> City Connections upon researching The Wheel. Caravans move along Forest and Jungle as if they were Roads.',
		unique1name: 'Longhouse',
		unique1icon: 'longhouse.png',
		unique1desc: 'Unique Iroquois Workshop<br />Cost: 100 <img src="img/civ/production.png"> or 500 <img src="img/civ/gold.png"><br />+2 <img src="img/civ/production.png"> Production<br />+1 <img src="img/civ/production.png"> Production from each worked Forest tile.',
		unique2name: 'Mohawk Warrior',
		unique2icon: 'mohawkwarrior.png',
		unique2desc: 'Unique Iroquois Swordsman<br />This Unit receives a major bonus when fighting on Forest and Jungle, unlike the Swordsman which it replaces. Also, unlike the Swordsman, it does not require Iron to build<br />Cost: 75 <img src="img/civ/production.png"> or 150 <img src="img/civ/faith.png"><br />Strength: 14 <img src="img/civ/strength.png"><br />Movement: 2 <img src="img/civ/movement.png">'
	}, {
		civName:'Japan',
		civIcon:'japan',
		leaderName: 'Oda Nobunaga',
		leaderIcon: 'oda',
		colorlight: '#FFFFFF',
		colordark: '#BBBBBB',
		fontcolor: '#B80000',
		abilityname: 'Bushido',
		ability: 'Units fight as though they were at full strength even when damaged. +1 <img src="img/civ/culture.png"> Culture from each Fishing Boat and +2 <img src="img/civ/culture.png"> Culture from each Atoll.',
		unique1name: 'Samurai',
		unique1icon: 'samurai.png',
		unique1desc: 'Unique Japanese Longswordsman<br />This Unit fights more effectively and helps produce Great Generals more quickly than the Longswordsman, which it replaces. Embarked Samurai can build Fishing Boats in one turn without being consumed.<br />Cost: 120 <img src="img/civ/production.png"> or 240 <img src="img/civ/faith.png"><br />Strength: 21 <img src="img/civ/strength.png"><br />Movement: 2 <img src="img/civ/movement.png">',
		unique2name: 'Zero',
		unique2icon: 'zero.png',
		unique2desc: 'Unique Japanese Fighter<br />This Unit has a bonus against other Fighters and does not require Oil.<br />Cost: 375 <img src="img/civ/production.png"><br />Strength: 45 <img src="img/civ/ranged.png"><br />Range: 8 <br />Movement: 2 <img src="img/civ/movement.png">'
	}, {
		civName:'Korea',
		civIcon:'korea',
		leaderName: 'Sejong',
		leaderIcon: 'sejong',
		colorlight: '#2a3398',
		colordark: '#191f5c',
		fontcolor: '#FF0000',
		abilityname: 'Scholars of the Jade Hall',
		ability: '+2 <img src="img/civ/science.png">science for all specialists and for all Great Person tile improvements. Receive a tech boost each time a scientific building/Wonder is built in the Korean capital.',
		unique1name: 'Turtle Ship',
		unique1icon: 'turtleship.png',
		unique1desc: 'Unique Korean Caravel<br />Heavily-armored naval unit of the Renaissance Era that is extremely difficult to kill. However Turtle Ships cannot enter deep ocean hexes outside of the city borders.<br />Cost: 120 <img src="img/civ/production.png"><br />Strength: 36 <img src="img/civ/strength.png"><br />Movement: 4 <img src="img/civ/movement.png">',
		unique2name: 'Hwach\'a',
		unique2icon: 'hwacha.png',
		unique2desc: 'Unique Korean Trebuchet<br />Anti-personnel rocket unit of the Medieval Era. Strong against land units, but weak against cities. <br />Cost: 120 <img src="img/civ/production.png"> or 240 <img src="img/civ/faith.png"><br />Strength: 11 <img src="img/civ/strength.png"> or 26 <img src="img/civ/ranged.png"><br />Range: 2 <br />Movement: 2 <img src="img/civ/movement.png">'
	}, {
		civName:'The Maya',
		civIcon:'maya',
		leaderName: 'Pacal',
		leaderIcon: 'pacal',
		colorlight: '#dab59a',
		colordark: '#8d5934',
		fontcolor: '#173E41',
		abilityname: 'The Long Count',
		ability: 'After researching Theology, receive a bonus Great Person at the end of every Maya Long Count calendar cycle (every 394 years). Each bonus person can only be chosen once.',
		unique1name: 'Pyramid',
		unique1icon: 'pyramid.png',
		unique1desc: 'Unique Mayan Shrine.<br />Cost: 40 <img src="img/civ/production.png"> or 250 <img src="img/civ/gold.png"><br />Increases the research Science and peace Faith of a city, speeding Research and the civilization\'s acquisition of Religions.<br />+2<img src="img/civ/faith.png" class="ico">Faith<br />+2<img src="img/civ/science.png" class="ico">Science',
		unique2name: 'Atlatlist',
		unique2icon: 'atlatlist.png',
		unique2desc: 'Unique Mayan Archer<br /> It is cheaper and available sooner than the Archer. <br />Cost: 36 <img src="img/civ/production.png"> or 72 <img src="img/civ/faith.png"><br />Strength:7<img src="img/civ/ranged.png"> or 5<img src="img/civ/strength.png"><br />Movement: 2 <img src="img/civ/movement.png">'
	}, {
		civName:'Mongolia',
		civIcon:'mongolia',
		leaderName: 'Gengis Khan',
		leaderIcon: 'genghis',
		colorlight: '#70000b',
		colordark: '#470007',
		fontcolor: '#FF7800',
		abilityname: 'Mongol Terror',
		ability: '+30% <img src="img/civ/strength.png"> Combat Strength when fighting City-State units or attacking a City-State itself. All mounted units have +1 <img src="img/civ/movement.png"> Movement.',
		unique1name: 'Khan',
		unique1icon: 'khan.png',
		unique1desc: 'Unique Mongolian Great General<br />While providing the same combat bonuses as a normal Great General, the Khan moves at an increased rate and can heal adjacent units.',
		unique2name: 'Keshik',
		unique2icon: 'keshik.png',
		unique2desc: 'Unique Mongolian Knight<br />It possesses a strong ranged attack, increased movement rate, and earns promotions 50% faster. Unit battles also contribute double the amount of points towards earning a Great General.<br />Cost: 120 <img src="img/civ/production.png"> or 240 <img src="img/civ/faith.png"><br />Strength: 15 <img src="img/civ/strength.png"> or 16 <img src="img/civ/ranged.png"><br />Range: 2 <br />Movement: 5 <img src="img/civ/movement.png">'
	}, {
		civName:'Morocco',
		civIcon:'morocco',
		leaderName: 'Ahmad al-Mansur',
		leaderIcon: 'ahmad',
		colorlight: '#db0400',
		colordark: '#3d0100',
		fontcolor: '#27B24F',
		abilityname: 'Gateway to Africa',
		ability: 'Receives +3 Gold gold and +1 culture Culture for each Trade Route with a different civ or City-State. The Trade Route owners receive +2 gold Gold for each Trade Route sent to Morocco.' ,
		unique1name: 'Kasbah',
		unique1icon: 'kasbah.png',
		unique1desc: 'Unique Moroccan Tile Improvement<br />May only be built on desert<br />+1 <img src="img/civ/food.png"> Food<br />+1 <img src="img/civ/production.png"> Prodction<br />+1 <img src="img/civ/gold.png"> Gold',
		unique2name: 'Berber Cavalry',
		unique2icon: 'berbercavalry.png',
		unique2desc: 'Unique Moroccan Cavalry<br />Cost: 255 <img src="img/civ/production.png"> or 450 <img src="img/civ/faith.png"><br />Receives combat bonuses when fighting both in Desert tiles and Moroccan territory.<br />Strength: 34 <img src="img/civ/strength.png"><br />Movement: 4 <img src="img/civ/movement.png">'
	}, {
		civName:'The Netherlands',
		civIcon:'netherlands',
		leaderName: 'William',
		leaderIcon: 'william',
		colorlight: '#ffa229',
		colordark: '#cc7400',
		fontcolor: '#FFFFFF',
		abilityname: 'Dutch East India Company',
		ability: 'Retains 50% of the <img src="img/civ/happiness.png"> Happiness benefits from a Luxury Resource if your last copy of it is traded away.',
		unique1name: 'Polder',
		unique1icon: 'polder.png',
		unique1desc: 'Unique Dutch Tile Improvement<br />May only be built on Marsh or Flood Plains<br />+3 <img src="img/civ/food.png"> Food<br />+1 <img src="img/civ/production.png"> Production after Economics<br />+2 <img src="img/civ/gold.png"> Gold after Economics',
		unique2name: 'Sea Beggar',
		unique2icon: 'seabeggar.png',
		unique2desc: 'Unique Dutch Privateer<br />Heals outside friendly territory. Starts with the first two Coastal Raider promotions allowing it to earn gold from attacking coastal cities. May capture any enemy naval units it defeats as prize ships.<br />Cost: 150 <img src="img/civ/production.png"><br />Strength: 25 <img src="img/civ/strength.png"><br />Movement: 5 <img src="img/civ/movement.png">'
	}, {
		civName:'The Ottomans',
		civIcon:'ottoman',
		leaderName: 'Suleiman',
		leaderIcon: 'suleiman',
		colorlight: '#fbfce4',
		colordark: '#eff089',
		fontcolor: '#12521E',
		abilityname: 'Barbary Corsairs',
		ability: 'All melee naval units have the Prize Ships promotion, allowing them to capture defeated ships. Pay only one-third the usual cost for naval unit maintenance.',
		unique1name: 'Janissary',
		unique1icon: 'janissary.png',
		unique1desc: 'Unique Ottoman Musketman<br />This Unit is stronger on offense and heals when it kills an enemy.<br />Cost: 150 <img src="img/civ/production.png"> or 300 <img src="img/civ/faith.png"><br />Strength: 24 <img src="img/civ/strength.png"><br />Movement: 2 <img src="img/civ/movement.png">',
		unique2name: 'Sipahi',
		unique2icon: 'sipahi.png',
		unique2desc: 'Unique Ottoman Lancer<br />This Unit is faster and can see further than the Lancer, which it replaces.<br />Cost: 185 <img src="img/civ/production.png"> or 370 <img src="img/civ/faith.png"><br />Strength: 25 <img src="img/civ/strength.png"><br />Movement: 5 <img src="img/civ/movement.png">'
	}, {
		civName:'Persia',
		civIcon:'persia',
		leaderName: 'Darius I',
		leaderIcon: 'darius',
		colorlight: '#d30703',
		colordark: '#7e0402',
		fontcolor: '#F5E637',
		abilityname: 'Achaemenid Legacy',
		ability: '<img src="img/civ/golden_age.png"> Golden Ages last 50% longer. During a Golden Age, units receive +1 <img src="img/civ/movement.png"> Movement and a +10% <img src="img/civ/strength.png"> Combat Strength bonus.',
		unique1name: 'Satrap\'s Court',
		unique1icon: 'satrapscourt.png',
		unique1desc: 'Unique Persian Bank<br />Cost: 200 <img src="img/civ/production.png"> or 780 <img src="img/civ/gold.png"><br />+2 <img src="img/civ/happiness.png"> Happiness<br />+3 <img src="img/civ/gold.png"> Gold<br />+25% <img src="img/civ/gold.png"> Gold per turn',
		unique2name: 'Immortal',
		unique2icon: 'immortal.png',
		unique2desc: 'Unique Persian Spearman<br />This Unit has a higher Strength and heals more quickly than the Spearman, which it replaces.<br />Cost: 56 <img src="img/civ/production.png"> or 112 <img src="img/civ/faith.png"><br />Strength: 12 <img src="img/civ/strength.png"><br />Movement: 2 <img src="img/civ/movement.png">'
	}, {
		civName:'Poland',
		civIcon:'poland',
		leaderName: 'Casimir III',
		leaderIcon: 'casimir',
		colorlight: '#ff4a47',
		colordark: '#750200',
		fontcolor: '#380000',
		abilityname: 'Solidarity',
		ability: 'Receive a free Social Policy at the start of each new Era.',
		unique1name: 'Ducal Stable',
		unique1icon: 'ducalstable.png',
		unique1desc: 'Unique Polish Stable.<br />Cost: 75 <img src="img/civ/production.png"> or 320 <img src="img/civ/gold.png"><br />+15% <img src="img/civ/production.png"> Production and +15 XP for Mounted Units. <br />Each Pasture worked by this City produces +1 <img src="img/civ/production.png"> Production and +1 <img src="img/civ/gold.png"> Gold.',
		unique2name: 'Winged Hussar',
		unique2icon: 'wingedhussar.png',
		unique2desc: 'Unique Polish Lancer.<br />Forces defenders to retreat when it inflicts more damage than it receives. <br />Cost: 185 <img src="img/civ/production.png"> or 370 <img src="img/civ/faith.png"><br />Strength: 28 <img src="img/civ/strength.png"><br />Movement: 5 <img src="img/civ/movement.png">'
	}, {
		civName:'Polynesia',
		civIcon:'polynesia',
		leaderName: 'Kamehameha',
		leaderIcon: 'kamehameha',
		colorlight: '#ff6600',
		colordark: '#c24e00',
		fontcolor: '#FFFF4A',
		abilityname: 'Wayfinding',
		ability: 'Can embark and move over Oceans immediately. +1 Sight when embarked. +10% <img src="img/civ/strength.png"> Combat Strength bonus if within 2 tiles of a Moai.',
		unique1name: 'Moai',
		unique1icon: 'moai.png',
		unique1desc: 'Unique Polynesian Tile Improvement<br />May only be build on coastal tiles<br />+1 <img src="img/civ/culture.png"> Culture<br />+1 <img src="img/civ/culture.png"> additional Culture for each adjacent Moai<br />+1 <img src="img/civ/gold.png"> Gold after Flight',
		unique2name: 'Maori Warrior',
		unique2icon: 'maoriwarrior.png',
		unique2desc: 'Unique Polynesian Warrior<br />Ancient Era unit that strikes fear into nearby enemies making them less effective in combat.<br />Cost: 40 <img src="img/civ/production.png"> or 80 <img src="img/civ/faith.png"><br />Strength: 8 <img src="img/civ/strength.png"><br />Movement: 2 <img src="img/civ/movement.png">'
	}, {
		civName:'Portugal',
		civIcon:'portugal',
		leaderName: 'Maria I',
		leaderIcon: 'maria',
		colorlight: '#FFFFFF',
		colordark: '#BBBBBB',
		fontcolor: '#03147C',
		abilityname: 'Mare Clausum',
		ability: 'Resource diversity grants twice as much <img src="img/civ/gold.png"> Gold for Portugal in Trade Routes.',
		unique1name: 'Feitoria',
		unique1icon: 'feitoria.png',
		unique1desc: 'Unique Portuguese Tile Improvement<br />May only be built in a City-State\'s lands, on a coastal tile without a resource. It provides one copy of each Luxury Resource type that the City-State has connected, regardless of your status with that City-State, but that copy cannot be traded.',
		unique2name: 'Nau',
		unique2icon: 'nau.png',
		unique2desc: 'Unique Portuguese Caravel<br />It has more <img src="img/civ/movement.png"> Movement than the Caravel, which it replaces, and can perform a one-time ability next to foreign lands to earn <img src="img/civ/gold.png"> Gold and XP.<br />Cost: 120 <img src="img/civ/production.png"> or  <img src="img/civ/faith.png"><br />Strength: 20 <img src="img/civ/strength.png"><br />Movement: 5 <img src="img/civ/movement.png">'
	}, {
		civName:'Rome',
		civIcon:'rome',
		leaderName: 'Augustus Caesar',
		leaderIcon: 'augustus',
		colorlight: '#6200a3',
		colordark: '#3a0061',
		fontcolor: '#EFC600',
		abilityname: 'The Glory of Rome',
		ability: '+25% <img src="img/civ/production.png"> Production towards any buildings that already exist in the <img src="img/civ/capital.png"> Capital.',
		unique1name: 'Ballista',
		unique1icon: 'ballista.png',
		unique1desc: 'Unique Roman Catpult<br />This Unit has a higher <img src="img/civ/ranged.png"> Ranged Combat Strength than the Catapult, which it replaces.<br />Cost: 75 <img src="img/civ/production.png"> or 150 <img src="img/civ/faith.png"><br />Strength: 8 <img src="img/civ/strength.png"> or 10 <img src="img/civ/ranged.png"><br />Range: 2<br />Movement: 2 <img src="img/civ/movement.png">',
		unique2name: 'Legion',
		unique2icon: 'legion.png',
		unique2desc: 'Unique Roman Swordsman<br />This Unit has a higher Strength than the Swordsman, which it replaces.<br />Cost: 75 <img src="img/civ/production.png"> or 150 <img src="img/civ/faith.png"><br />Strength: 17 <img src="img/civ/strength.png"><br />Movement: 2 <img src="img/civ/movement.png">'
	}, {
		civName:'Russia',
		civIcon:'russia',
		leaderName: 'Catherine',
		leaderIcon: 'catherine',
		colorlight: '#ffc61a',
		colordark: '#bd8e00',
		fontcolor: '#000000',
		abilityname: 'Siberian Riches',
		ability: 'Strategic Resources provide +1 <img src="img/civ/production.png"> Production and Horse, Iron and Uranium Resources provide double quantity.',
		unique1name: 'Krepost',
		unique1icon: 'krepost.png',
		unique1desc: 'Unique Russian Barracks<br />Cost: 75 <img src="img/civ/production.png"> or 400 <img src="img/civ/gold.png"><br />+15 XP for all Units.<br /><img src="img/civ/culture.png"> Culture and <img src="img/civ/gold.png"> Gold costs of acquiring new tiles reduced by 25% in this city.',
		unique2name: 'Cossack',
		unique2icon: 'cossack.png',
		unique2desc: 'Unique Russian Cavalry<br />This Unit has a combat bonus when fighting enemies that have already taken damage.<br />Cost: 225 <img src="img/civ/production.png"> or 450 <img src="img/civ/faith.png"><br />Strength: 34 <img src="img/civ/strength.png"><br />Movement: 4 <img src="img/civ/movement.png">'
	}, {
		civName:'The Shoshone',
		civIcon:'shoshone',
		leaderName: 'Pocatello',
		leaderIcon: 'pocatello',
		colorlight: '#65503e',
		colordark: '#392d23',
		fontcolor: '#18EFCE',
		abilityname: 'Great Expanse',
		ability: 'Founded cities start with additional territory. Units receive a combat bonus when fighting within their own territory.',
		unique1name: 'Pathfinder',
		unique1icon: 'pathfinder.png',
		unique1desc: 'Unique Shoshone Scout<br />Excellent at exploring and fearsome in combat. It possesses a promotion that allows it to choose the benefit when uncovering an ancient ruin.<br />Cost: 45 <img src="img/civ/production.png"> or 50 <img src="img/civ/faith.png"><br />Strength: 8 <img src="img/civ/strength.png"><br />Movement: 2 <img src="img/civ/movement.png">',
		unique2name: 'Comanche Riders',
		unique2icon: 'comancheriders.png',
		unique2desc: 'Unique Shoshone Cavalry<br />Cheaper and faster than the base unit.<br />Cost: 200 <img src="img/civ/production.png"> or 450 <img src="img/civ/faith.png"><br />Strength: 34 <img src="img/civ/strength.png"><br />Movement: 4 <img src="img/civ/movement.png">'
	}, {
		civName:'Siam',
		civIcon:'siam',
		leaderName: 'Ramkhamhaeng',
		leaderIcon: 'ramkhamhaeng',
		colorlight: '#f6e95a',
		colordark: '#f2df0d',
		fontcolor: '#B00703',
		abilityname: 'Father Governs Children',
		ability: '<img src="img/civ/food.png"> Food, <img src="img/civ/culture.png"> Culture, and <img src="img/civ/faith.png"> Faith from friendly City-States increased by 50%.',
		unique1name: 'Wat',
		unique1icon: 'wat.png',
		unique1desc: 'Unique Siamese University<br />Cost: 160 <img src="img/civ/production.png"> or 200 <img src="img/civ/faith.png"><br />+3 <img src="img/civ/culture.png"> Culture<br />+2 <img src="img/civ/science.png"> from jungle tiles<br />+33% <img src="img/civ/science.png"> Science',
		unique2name: 'Naresuan\'s Elephant',
		unique2icon: 'naresuan.png',
		unique2desc: 'Unique Siamese Knight<br />This Unit receives a bonus against other mounted Units and has a higher <img src="img/civ/strength.png"> Combat Strength than the Knight, which it replaces.<br />Cost: 120 <img src="img/civ/production.png"> or 240 <img src="img/civ/faith.png"><br />Strength: 25 <img src="img/civ/strength.png"><br />Movement: 3 <img src="img/civ/movement.png">'
	}, {
		civName:'Songhai',
		civIcon:'songhai',
		leaderName: 'Askia',
		leaderIcon: 'askia',
		colorlight: '#eba014',
		colordark: '#b27910',
		fontcolor: '#5A0009',
		abilityname: 'River Warlord',
		ability: 'Receive triple <img src="img/civ/gold.png"> Gold from Barbarian encampments and pillaging Cities. Land units gain the War Canoe and Amphibious promotions, strengthening them while embarked.',
		unique1name: 'Mud Pyramid Mosque',
		unique1icon: 'mudpyramidmosque.png',
		unique1desc: 'Unique Songhai Temple<br />Cost: 100 <img src="img/civ/production.png"> or 500 <img src="img/civ/gold.png"><br /> The Mud Pyramid Mosque greatly increases the city\'s culture Culture, speeding the growth of the city\'s territory and the civilization\'s acquisition of Social Policies. The Mud Pyramid Mosque has no maintenance costs.<br />+2 <img src="img/civ/culture.png"> Culture<br />+2 <img src="img/civ/faith.png"> Faith',
		unique2name: 'Mandekalu Cavalry',
		unique2icon: 'mandekalucavalry.png',
		unique2desc: 'Unique Songhai Knight<br />This Unit is not penalized when attacking Cities, unlike the Knight which it replaces.<br />Cost: 110 <img src="img/civ/production.png"> or 220 <img src="img/civ/faith.png"><br />Strength: 20 <img src="img/civ/strength.png"><br />Movement: 4 <img src="img/civ/movement.png">'
	}, {
		civName:'Spain',
		civIcon:'spain',
		leaderName: 'Isabella',
		leaderIcon: 'isabella',
		colorlight: '#802828',
		colordark: '#3e1414',
		fontcolor: '#FFA8A8',
		abilityname: 'Seven Cities of Gold',
		ability: '<img src="img/civ/gold.png"> Gold bonus for discovering a Natural Wonder (bonus enhanced if first to discover it). <img src="img/civ/culture.png"> Culture, <img src="img/civ/happiness.png"> Happiness, and tile yields from Natural Wonders doubled.',
		unique1name: 'Tercio',
		unique1icon: 'tercio.png',
		unique1desc: 'Unique Spanish Musketman<br /> This Unit has a higher Strength than the Musketman which it replaces, as well as a Bonus vs Mounted promotion.<br />Cost: 160 <img src="img/civ/production.png"> or 320 <img src="img/civ/faith.png"><br />Strength: 26 <img src="img/civ/strength.png"><br />Movement: 2 <img src="img/civ/movement.png">',
		unique2name: 'Conquistador',
		unique2icon: 'conquistador.png',
		unique2desc: 'Unique Spanish Knight<br />It has extra visibility, the ability to found new cities on a foreign continents, the defensive embarkation promotion, and also suffers no penalty when attacking cities.<br />Cost: 135 <img src="img/civ/production.png"> or 270 <img src="img/civ/faith.png"><br />Strength: 20 <img src="img/civ/strength.png"><br />Movement: 4 <img src="img/civ/movement.png">'
	}, {
		civName:'Sweden',
		civIcon:'sweden',
		leaderName: 'Gustavus Adolphus',
		leaderIcon: 'gustavus',
		colorlight: '#0808c4',
		colordark: '#040467',
		fontcolor: '#F8F602',
		abilityname: 'Nobel Prize',
		ability: 'Gain 90 <img src="img/civ/influence.png"> Influence with a Great Person gift to a City-State. When declaring friendship, Sweden and their friend gain a +10% boost to Great Person generation.',
		unique1name: 'Hakkapeliitta',
		unique1icon: 'hakkapeliitta.png',
		unique1desc: 'Unique Swedish Lancer<br />Elite mounted Unit that specializes in working with Great Generals.<br />Cost: 185 <img src="img/civ/production.png"> or 370 <img src="img/civ/faith.png"><br />Strength: 25 <img src="img/civ/strength.png"><br />Movement: 4 <img src="img/civ/movement.png">',
		unique2name: 'Carolean',
		unique2icon: 'carolean.png',
		unique2desc: 'Unique Swedish Rifleman<br />Starts with the March promotion that allows it to Heal every turn, even if it performs an action.<br />Cost: 225 <img src="img/civ/production.png"><br />Strength: 34 <img src="img/civ/strength.png"><br />Movement: 2 <img src="img/civ/movement.png">'
	}, { 
		civName:'Venice',
		civIcon:'venice',
		leaderName: 'Enrico Dandolo',
		leaderIcon: 'enrico',
		colorlight: '#7827be',
		colordark: '#501a7f',
		fontcolor: '#FFFED7',
		abilityname: 'Serenissima',
		ability: 'Cannot gain settlers nor annex cities. Double the normal number of trade routes available. A Merchant of Venice appears after researching Optics. May purchase in puppeted cities.',
		unique1name: 'Merchant of Venice',
		unique1icon: 'merchantofvenice.png',
		unique1desc: 'Unique Venician Great Merchant<br />Aside from the ability to Conduct a Trade Mission, the Merchant of Venice can purchase City-States outright, bringing them under Venetian control as a Puppet.',
		unique2name: 'Great Galleass',
		unique2icon: 'greatgalleass.png',
		unique2desc: 'Unique Venician <br />Better at attacking and defending than the normal Galleass it replaces, but more expensive.<br />Cost: 110 <img src="img/civ/production.png"><br />Strength: 18 <img src="img/civ/strength.png"> or 20 <img src="img/civ/ranged.png"><br />Range: 2 <br />Movement: 3 <img src="img/civ/movement.png">'
	}, {
		civName:'The Zulus',
		civIcon:'zulu',
		leaderName: 'Shaka',
		leaderIcon: 'shaka',
		colorlight: '#ffeee0',
		colordark: '#ffbf8f',
		fontcolor: '#6A3118',
		abilityname: 'Iklwa',
		ability: 'Melee units cost 50% less maintenance. All units require 25% less experience to earn their next promotion.',
		unique1name: 'Ikanda',
		unique1icon: 'ikanda.png',
		unique1desc: 'Unique Zulu Barracks<br />Cost: 75 <img src="img/civ/production.png"> or 400 <img src="img/civ/faith.png"><br />Grants a unique set of promotions to pre-gunpowder melee units created within the city. These include faster movement, and greater combat strength.',
		unique2name: 'Impi',
		unique2icon: 'impi.png',
		unique2desc: 'Unique Zulu Pikeman<br />Before engaging in melee, the Impi performs a spear throw attack that can damage or kill the enemy unit before making contact.<br />Cost: 90 <img src="img/civ/production.png"> or 180 <img src="img/civ/faith.png"><br />Strength: 16 <img src="img/civ/strength.png"><br />Movement: 2 <img src="img/civ/movement.png">'
	}];
}]);

civApp.filter("sanitize", ["$sce", function($sce) {
	return function(htmlCode) {
		return $sce.trustAsHtml(htmlCode);
	};
}]);
